---
name: mcvs-golang-action
description: |
  The Mission Critical Vulnerability Scanner (MCVS) Golang action.
inputs:
  code_coverage_expected:
    description: |
      The minimum code coverage.
    default: "80"
  golang-unit-tests-exclusions:
    description: |
      The Golang paths that should be excluded from unit testing.
    default: " "
  golangci-lint-version:
    description: |
      The Golangci-lint version that has to be installed and used.
    default: v1.55.2
  golang-number-of-tests-in-parallel:
    description: |
      Number of test in parallel.
    default: "4"
  trivy-action-db:
    default: "ghcr.io/aquasecurity/trivy-db:2"
    description: |
      OCI repository to retrieve trivy-db from.
  trivy-action-java-db:
    description: |
      OCI repository to retrieve trivy-java-db from.
    default: "ghcr.io/aquasecurity/trivy-java-db:1"
  token:
    description: |
      A token is required to allow the mcvs-golang-action to pull the
      cached trivy DBs to prevent bump into pull rate limits.
    required: true
runs:
  using: "composite"
  steps:
    #
    # YAML linting.
    #
    - run: |
        pip install --user yamllint==1.35.1
        yamllint .
      shell: bash
    #
    # Install the golang version that has been defined in the go.mod file.
    #
    - uses: actions/setup-go@v5.0.2
      with:
        go-version-file: "go.mod"
        cache: false
    #
    # Verify downloaded dependencies.
    #
    - name: verify golang modules
      shell: bash
      run: |
        go mod verify
    - uses: golang/govulncheck-action@v1.0.3
      with:
        go-version-file: go.mod
        go-package: ./...
    #
    # Check for 'incorrect import order', let pipeline fail if true and provide
    # instruction to remediate it. Note: check is included in golangci-lint,
    # but it does not provide clarity how to resolve it when positive.
    #
    - name: gci
      shell: bash
      run: |
        go install github.com/daixiang0/gci@v0.13.4
        if ~/go/bin/gci list --skip-generated . | grep "\.go$"; then
          echo "One or more golang files detected with: 'incorrect import order':"
          echo " * Observe: '~/go/bin/gci diff --skip-generated .'"
          echo " * Resolve: '~/go/bin/gci write --skip-generated .'"
          exit 1
        fi
    #
    # Code security scanning.
    #
    - uses: anchore/scan-action@v5.0.0
      with:
        only-fixed: false
        output-format: table
        path: "."
        severity-cutoff: high
    - uses: 030/trivyignore-validator-action@v0.1.2
    - name: Log in to GitHub Packages Docker registry
      shell: bash
      run: |
        echo "${{ inputs.token }}" |\
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - uses: aquasecurity/trivy-action@0.24.0
      env:
        TRIVY_DB_REPOSITORY: ${{ inputs.trivy-action-db }}
        TRIVY_JAVA_DB_REPOSITORY: ${{ inputs.trivy-action-java-db }}
        TRIVY_PASSWORD: ${{ inputs.token }}
        TRIVY_USERNAME: ${{ github.actor }}
      with:
        scan-type: "fs"
        scan-ref: "."
        exit-code: "1"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"
        trivyignores: .trivyignore
    #
    # Run golangci-lint.
    #
    - uses: golangci/golangci-lint-action@v6.1.0
      with:
        args: |-
          --enable-all \
          --out-format=colored-line-number \
          --timeout 2m30s \
          -v
        version: ${{ inputs.golangci-lint-version }}
    #
    # Unit tests.
    #
    - name: unit tests
      shell: bash
      run: |
        go test \
          -p ${{ inputs.golang-number-of-tests-in-parallel }} \
          -race \
          -short \
          -v \
          $(go list ./... | grep -v '${{ inputs.golang-unit-tests-exclusions }}')
    #
    # Unit & integration tests including code coverage.
    #
    - name: unit & integrations tests and code coverage
      shell: bash
      run: |
        go test \
          -coverpkg=./... \
          -coverprofile=profile.cov \
          -p ${{ inputs.golang-number-of-tests-in-parallel }} \
          -race \
          -short \
          --tags=integration \
          -v \
          $(go list ./... | grep -v '${{ inputs.golang-unit-tests-exclusions }}')
        code_coverage_actual=$(go tool cover -func profile.cov |\
          grep total: |\
          awk '{print $3}' |\
          sed 's/%//')
        if (( $(echo "${{ inputs.code_coverage_expected }} > ${code_coverage_actual}" | bc -l) )); then
          echo "The actual code coverage: '${code_coverage_actual}' is too low. Expected: '${{ inputs.code_coverage_expected }}'."
          exit 1
        fi
