---
name: mcvs-golang-action
description: |
  The Mission Critical Vulnerability Scanner (MCVS) Golang action.
inputs:
  golang-unit-tests-exclusions:
    description: |
      The Golang paths that should be excluded from unit testing.
    default: ' '
  golangci-lint-version:
    description: |
      The Golangci-lint version that has to be installed and used.
    default: v1.55.2
    required: true
  golang-number-of-tests-in-parallel:
    description: |
      Number of test in parallel.
    default: '4'
runs:
  using: 'composite'
  steps:
    #
    # Install the golang version that has been defined in the go.mod file.
    #
    - uses: actions/setup-go@v5.0.1
      with:
        go-version-file: 'go.mod'
        cache: false
    #
    # Verify downloaded dependencies.
    #
    - name: verify golang modules
      shell: bash
      run: |
        go mod verify
    #
    # Check for 'incorrect import order', let pipeline fail if true and provide
    # instruction to remediate it. Note: check is included in golangci-lint,
    # but it does not provide clarity how to resolve it when positive.
    #
    - name: gci
      shell: bash
      run: |
        go install github.com/daixiang0/gci@v0.13.4
        if ~/go/bin/gci list --skip-generated . | grep "\.go$"; then
          echo "One or more golang files detected with: 'incorrect import order':"
          echo " * Observe: '~/go/bin/gci diff --skip-generated .'"
          echo " * Resolve: '~/go/bin/gci write --skip-generated .'"
          exit 1
        fi
    #
    # Code security scanning.
    #
    - uses: 030/trivyignore-validator-action@v0.1.2
    - uses: aquasecurity/trivy-action@0.17.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        trivyignores: .trivyignore
    #
    # Run golangci-lint.
    #
    - uses: golangci/golangci-lint-action@v6.0.1
      with:
        args: |-
          --enable-all \
          --out-format=colored-line-number \
          --timeout 2m30s \
          -v
        version: ${{ inputs.golangci-lint-version }}
    #
    # Unit tests.
    #
    - name: unit tests
      shell: bash
      run: |
        go test \
          -p ${{ inputs.golang-number-of-tests-in-parallel }} \
          -race \
          -short \
          -v \
          $(go list ./... | grep -v '${{ inputs.golang-unit-tests-exclusions }}')
    #
    # Both unit and integration tests including code coverage.
    #
    - name: unit & integrations tests and code coverage
      shell: bash
      run: |
        go test \
          --tags=integration \
          -cover \
          -covermode=atomic \
          -coverprofile=coverage.txt \
          -p ${{ inputs.golang-number-of-tests-in-parallel }} \
          -race \
          -short \
          -v \
          $(go list ./... | grep -v '${{ inputs.golang-unit-tests-exclusions }}')
