---
name: mcvs-golang-action
description: |
  The Mission Critical Vulnerability Scanner (MCVS) Golang action.
inputs:
  code-coverage-expected:
    default: "80"
    description: |
      The minimum code coverage.
  gci:
    default: "true"
    description: |
      Whether to check gci. Disable if the project provides an alternative way.
  golang-unit-tests-exclusions:
    default: " "
    description: |
      The Golang paths that should be excluded from unit testing.
  golangci-lint-version:
    default: v1.55.2
    description: |
      The Golangci-lint version that has to be installed and used.
  golang-number-of-tests-in-parallel:
    description: |
      Number of test in parallel.
  task-version:
    default: v3.39.2
    description: |
      The Task version that has to be installed and used.
  testing-type:
    description: |
      The testing type, e.g. integration, unit or some other.
  trivy-action-db:
    default: "ghcr.io/aquasecurity/trivy-db:2"
    description: |
      OCI repository to retrieve trivy-db from.
  trivy-action-java-db:
    description: |
      OCI repository to retrieve trivy-java-db from.
    default: "ghcr.io/aquasecurity/trivy-java-db:1"
  token:
    description: |
      A token is required to allow the mcvs-golang-action to pull the
      cached trivy DBs to prevent bump into pull rate limits.
runs:
  using: "composite"
  steps:
    #
    # Install task and the golang version that has been defined in the go.mod
    # file.
    #
    # yamllint disable rule:line-length
    - uses: actions/setup-go@v5.1.0
      if: inputs.testing-type == 'component' || inputs.testing-type == 'coverage' || inputs.testing-type == 'integration' || inputs.testing-type == 'lint' || inputs.testing-type == 'unit'
      with:
        go-version-file: "go.mod"
        cache: false
    - name: install task
      if: inputs.testing-type == 'component' || inputs.testing-type == 'coverage' || inputs.testing-type == 'integration' || inputs.testing-type == 'lint' || inputs.testing-type == 'unit'
      shell: bash
      run: |
        if ! ~/go/bin/task --version | grep -q "Task version: ${{ inputs.task-version }}"; then
          major_version=$(echo "${{ inputs.task-version }}" | sed -E 's/^v([0-9]+).*/\1/')
          go install github.com/go-task/task/v${major_version}/cmd/task@${{ inputs.task-version }}
        fi
    # yamllint enable rule:line-length
    #
    # Verify downloaded dependencies.
    #
    - name: verify golang modules
      if: inputs.testing-type == 'security-golang-modules'
      shell: bash
      run: |
        go mod verify
    - uses: golang/govulncheck-action@v1.0.4
      if: inputs.testing-type == 'security-golang-modules'
      with:
        go-version-file: go.mod
        go-package: ./...
    #
    # Check for 'incorrect import order', let pipeline fail if true and provide
    # instruction to remediate it. Note: check is included in golangci-lint,
    # but it does not provide clarity how to resolve it when positive.
    #
    - name: gci
      if: inputs.gci == 'true' && inputs.testing-type == 'lint'
      shell: bash
      env:
        TASK_X_REMOTE_TASKFILES: 1
      run: |
        task remote:gci --yes
    #
    # Code security scanning.
    #
    # * Grype
    #
    - uses: anchore/scan-action@v5.2.1
      if: inputs.token != '' && inputs.testing-type == 'security-grype'
      with:
        only-fixed: false
        output-format: table
        path: "."
        severity-cutoff: high
    #
    # * Trivy
    #
    - uses: 030/trivyignore-validator-action@v0.1.2
      if: inputs.token != '' && inputs.testing-type == 'security-trivy'
    - name: Log in to GitHub Packages Docker registry
      if: inputs.token != '' && inputs.testing-type == 'security-trivy'
      shell: bash
      run: |
        echo "${{ inputs.token }}" |\
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
    #
    # Duplicated trivy-action parameters as GitHub actions do NOT support
    # anchors: https://github.com/actions/runner/issues/1182
    #
    - uses: aquasecurity/trivy-action@0.28.0
      if: inputs.token != '' && inputs.testing-type == 'security-trivy'
      env:
        TRIVY_DB_REPOSITORY: ${{ inputs.trivy-action-db }}
        TRIVY_JAVA_DB_REPOSITORY: ${{ inputs.trivy-action-java-db }}
        TRIVY_PASSWORD: ${{ inputs.token }}
        TRIVY_USERNAME: ${{ github.actor }}
      with:
        scan-type: "fs"
        scan-ref: "."
        exit-code: "1"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"
        trivyignores: .trivyignore
    - uses: aquasecurity/trivy-action@0.28.0
      if: inputs.token == '' && inputs.testing-type == 'security-trivy'
      env:
        TRIVY_DB_REPOSITORY: ${{ inputs.trivy-action-db }}
        TRIVY_JAVA_DB_REPOSITORY: ${{ inputs.trivy-action-java-db }}
      with:
        scan-type: "fs"
        scan-ref: "."
        exit-code: "1"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"
        trivyignores: .trivyignore
    #
    # Run golangci-lint.
    #
    - name: golangci-lint
      if: inputs.testing-type == 'lint'
      shell: bash
      env:
        TASK_X_REMOTE_TASKFILES: 1
      run: |
        task remote:golangci-lint --yes
    #
    # Unit tests.
    #
    - name: unit tests
      if: inputs.testing-type == 'unit'
      shell: bash
      env:
        TASK_X_REMOTE_TASKFILES: 1
      run: |
        task remote:test --yes
    #
    # Integration tests.
    #
    - name: integration tests
      if: inputs.testing-type == 'integration'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        task remote:test-integration --yes
    #
    # Coverage.
    #
    - name: code coverage
      if: inputs.testing-type == 'coverage'
      shell: bash
      env:
        CODE_COVERAGE_EXPECTED: ${{ inputs.code-coverage-expected }}
        CODE_COVERAGE_FILE_EXCLUSIONS: ${{ inputs.golang-unit-tests-exclusions }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        task remote:coverage --yes
    #
    # Component tests.
    #
    - name: component tests
      if: inputs.testing-type == 'component'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        task remote:test-component --yes
